### ISSUE TITLE
wrong number of arguments(0 for 3..4) barchat

### ISSUE THREAD

**Issue by ghost** [Guidecase/jqplot-rails#1]
<%= plot2 = [ [[2,1], [4,2], [6,3], [3,4]],[[5,1], [1,2], [3,3], [4,4]],[[4,1], [7,2], [1,3], [2,4]]] %>
<%= jqplot 200,200,data1, {:seriesDefaults => {:renderer=> jqplot.BarRenderer,trendline:{ show: true },:rendererOptions=> {:diameter=>12,:show    DataLabels=> true}}, legend: {show: true}} %>

I am trying to implement jqplot as Bar renderer but i am getting this wrong number of argument error

**Comment by TertiumQuid** [comment]
On first glance I'd guess that you need to wrap the "jqplot.BarRenderer" argument in quotes to make it a string.

**Comment by ghost** [comment]
Now i am getting TypeError

TypeError: this.renderer.init is undefined
this.renderer.init.call(this, this.rendererOptions, plot);

**Comment by TertiumQuid** [comment]
As described in the README you will need to explicitly include the desired renderers in your manifest file; this plugin errors on the side of loading only the minimal javascript necessary. 

//= require plugins/jqplot.barRenderer.js

**Comment by srinidhibs** [comment]
Including plugins doesn't help in this case. All these renderers need to be eval()d - just like options.seriesDefaults.renderer is eval()d.
